name: package Addon

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Package
        uses: BigWigsMods/packager@master
        env:
          # This section might already create other env variables, just append the WAGO_API_TOKEN to these
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
